# Use heroku Config Vars
line.bot:
  channel-token: ${LINE_BOT_CHANNEL-TOKEN}
  channel-secret: ${LINE_BOT_CHANNEL-SECRET}
  handler.path: ${LINE_BOT_HANDLER_PATH}
  yahoojp-appid: ${LINE_BOT_YAHOOJP_APP_ID}
  giphy-app-key: ${LINE_BOT_GIPHY_APP_KEY}
